{"name": "Проверка получения заказа с неверными параметрами", "status": "passed", "parameters": [{"name": "response_expected", "value": "{'code': 404, 'message': 'Заказ не найден'}"}, {"name": "params", "value": "{'t': 0}"}], "start": 1758314380765, "stop": 1758314380880, "uuid": "754e0f15-9777-440d-9899-81a33a9b5dd8", "historyId": "47c477045bf5239dc1e1a743c94a13e7", "testCaseId": "c79a7dadd3f5f15dcde2c813d01e18ec", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_by_wrong_track", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "7372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}], "titlePath": ["tests", "test_get_order.py", "TestGetOrder"]}