{"name": "Проверка присвоения заказа с неверными параметрами", "status": "passed", "parameters": [{"name": "response_expected", "value": "{'code': 404, 'message': 'Курьера с таким id не существует'}"}, {"name": "wrong_data", "value": "{'courierId': -1}"}], "start": 1758314305509, "stop": 1758314305847, "uuid": "d0c6fb42-96d9-4f42-81cf-9ea4601f8dc1", "historyId": "cad7d26a236ca2f330f9022c9fe2a371", "testCaseId": "95ac7c73cec1d8ec3815307c1194dfc5", "fullName": "tests.test_courier_accept_orders.TestCourierAcceptOrder#test_courier_accept_order_with_wrong_params", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_accept_orders"}, {"name": "subSuite", "value": "TestCourierAcceptOrder"}, {"name": "host", "value": "DESKTOP-U7O3CJE"}, {"name": "thread", "value": "7372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_accept_orders"}], "titlePath": ["tests", "test_courier_accept_orders.py", "TestCourierAcceptOrder"]}